### ISSUE TITLE
Section 5. Component, State, Props 

### ISSUE THREAD

**Issue by dhflxhdxhd** [dhflxhdxhd/basic-React#3]
## Description 
Component, State, Props 등의 React의 기본 개념 정리

## Todo 
- [x] docs: section 5 강의 수강
- [x] docs: React 기본 개념 notion 정리
- [x] feat: basic 코드 적용

**Comment by dhflxhdxhd** [comment]
**5강 수강 완료 !**
